### ISSUE TITLE
How do I run this project?

### ISSUE THREAD

**Issue by LeePower** [beaverden/Taxi#1]
Hi, thanks for the work.
How do I run it?
After I run`composer install`
and run it, it gives me 
`Whoops, looks like something went wrong.`
Any heads up?

**Comment by beaverden** [comment]
Hi there, Lee. First of all, I appreciate the attention.
Secondly, although  the comments are written in English, the whole site UI is on Russian, so today I'll work on that.
Then I'll look up for a correct project export and inform you when it's ready.

**Comment by beaverden** [comment]
The issue must had appeared because I have never focused on a right export, but now I will

**Comment by beaverden** [comment]
It looks like `composer install` didn't take care of `.env` file, whose absence was generating the error

**Comment by beaverden** [comment]
I have added a guide for installation that worked for me and translated the project to English (you still have to search for a new logo). Hope it works.

**Comment by LeePower** [comment]
Everything works now! Thanks for the effort!
