### ISSUE TITLE
what is the .htacess

### ISSUE THREAD

**Issue by jogj4dev** [beaverden/Taxi#2]
its cool, very simpel booking taxi. What is the .htacess?

**Comment by beaverden** [comment]
I think it is the default one.
Though remember, this is just a simple test project, please consider improving the security on the project if you want to use this is any releases.

**Comment by jogj4dev** [comment]
Dear denis,

Thankyou very much, may I edit your script? I want to have therapist on
demand app like uber massage

On Fri, Nov 3, 2017 at 2:40 AM, Denis Rozimovschii <notifications@github.com

**Comment by beaverden** [comment]
Of course you can.
