### ISSUE TITLE
Giving advice on how to run this project in the current year

### ISSUE THREAD

**Issue by JermFlerm** [beaverden/Taxi#3]
Good day, I am a student who is currently working on a taxi service app. I was trying to use your project as a guide but have been running into many issues trying to just get it to run. Do you have any advice on what I need to do seeing that many things have changed over the years?

**Comment by beaverden** [comment]
Hello, I haven't supported this project for years, indeed. I will attempt
to install it myself and will come back to you with answers.

Regards,
Rozimovschii Denis

**Comment by JermFlerm** [comment]
Thank you for replying. I had tried making the changes I saw about gulp, the change from elixir to mix, and tried updating certain things in it but the list of errors were great, some of them were:

- Package illuminate/html is abandoned, you should avoid using it. Use laravelcollective/html instead.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

- Warning: Ambiguous class resolution, "AddIpColumn" was found in both "C:/xampp/htdocs/Sample Taxi/Taxi-master/database/migrations/comments/2015_11_10_221931_add_ip_column.php" and "C:/xampp/htdocs/Sample Taxi/Taxi-master/database/migrations/orders/2015_11_04_212705_add_ip_column.php", the first will be used.

And other errors about deprecated gulp, minify, minimatch, and cryptiles

**Comment by beaverden** [comment]
I have added a fix for the class collision. Pull the changes and try to re-run all the steps from the readme and it should work.

**Comment by JermFlerm** [comment]
Sorry to bother you again, I ran all the steps and created the database and all but it just won't open it through local host. I set up the virtual hosts and all but it gives me errors from the "Connection.php" file. I did the migration and it only migrated the firewall and migrations table. I tried doing a seed and nothing was added. Am I doing something wrong? 
And then I tried making the changes to gulp by trying to update it and the other deprecated things, they just won't update.
Let me try reading again

**Comment by beaverden** [comment]
I suggest reinstalling the project (maybe you made some changes that generate errors) and re-run the steps. Also check the php version of your XAMPP

`PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies`

**Comment by JermFlerm** [comment]
Thank you very much for being so patient with me sir, It is now working. I had to basically reinstall xampp, took me some time but it's working! Sorry for bothering you again, I just didn't realise how specific these things are.
